### ISSUE TITLE
Rescaling is laggy

### ISSUE THREAD

**Issue by Yasamato** [software-challenge/gui#2]
This issue is caused due to the automated resizing of all images (newly loaded, scaled to fit, rotated and flipped) and this is for every event (one resize with mouse drag can triggers hundreds of those events).

This will not be fixed or addressed in the near feature by me at least.
If you have an idea how to fix it: give it a try ✈️

**Comment by xerus2000** [comment]
svg?

**Comment by xeruf** [comment]
Probably out of date
