### ISSUE TITLE
Make canvas of pento-i same size as the rest

### ISSUE THREAD

**Issue by SKoschnicke** [software-challenge/gui#30]
![image](https://user-images.githubusercontent.com/105162/94127666-7794b400-fe59-11ea-9b1b-7522f38dd38a.png)

**Comment by Estugon** [comment]
We could possibly make all the containers one block larger (as in: 5x5 block containers), so the pento-I fits in these containers, too.
This would make this whole menu a bit more consistent, and there wouldn't be any more glitches when turning the pento-i.

**Comment by xeruf** [comment]
out of date
