### ISSUE TITLE
Going back in game history and then hitting "Weiter" leads to disqualification

### ISSUE THREAD

**Issue by SKoschnicke** [software-challenge/gui#70]
Human vs. GUI started client (simpleclient)
GUI version 21.3.3

Create a game, play some rounds. Then press the "Back" buttons multiple times. Then press "Weiter".

Expected that the game would continue, waiting for the human to make their next turn.

But got a message that the game ended with "Regelverletzung".

This is an edge case, so no high priority (working replays is more important). But wanted to record it.

**Comment by xeruf** [comment]
Pretty sure this is fixed
