### ISSUE TITLE
Add help popup from menubar

### ISSUE THREAD

**Issue by xeruf** [software-challenge/gui#73]
Replaces game-specific information from https://docs.software-challenge.de/server.html#die-programmoberfl%C3%A4che and lists shortcuts

**Comment by xeruf** [comment]
Partially implemented in https://github.com/software-challenge/gui/commit/0c7a4a5ccfa43f5a5b3fd8b26b5ce7eba74cbed7

**Comment by xeruf** [comment]
Siehe commit oben, aktuell ein minimaler Dialog in Hilfe>Bedienungsanleitung

**Comment by niklasCarstensen** [comment]
Shortcuts werden bereits angeziegt und Hilfe ist Spiel-unspeziefisch
