### ISSUE TITLE
Error when starting game "manual vs. human"

### ISSUE THREAD

**Issue by SKoschnicke** [software-challenge/gui#74]
When trying to start a game with player one "manually started" and player two "human" I get "Error in java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)".

Started from main branch commit acad3b9

![image](https://user-images.githubusercontent.com/105162/124101084-4b006f00-da5f-11eb-8684-684fac699226.png)

**Comment by xeruf** [comment]
I get no such error. Is your backend up-to-date?

    git submodule update --init --recursive

**Comment by SKoschnicke** [comment]
Seems I had an old build lying around in the backend submodule. It was only removed by changing into the backend submodule and executing `./gradlew clean`.

**Comment by xeruf** [comment]
> Seems I had an old build lying around in the backend submodule. It was only removed by changing into the backend submodule and executing `./gradlew clean`.

I am actually pushing a fix to this soon, the backend so far didn't recognize version updates in some cases and did not rebuild.
