### ISSUE TITLE
Überlappung von Spielsegmenten

### ISSUE THREAD

**Issue by jgeramb** [software-challenge/gui#99]
### Problem

Das 8. Segment teilt sich ein Feld mit dem 3. Segment auf dem Spielfeld, wodurch dem Feld kein eindeutiges Segment zugewiesen werden kann.

![Screenshot mit markierter Überlappung](https://github.com/software-challenge/gui/assets/30385979/6e9150ce-258d-44d5-8659-40b70c28f979)

### Erwartetes Ergebnis

Die Richtung wird so lange neu ausgelost, bis es keine Überlappungen mehr gibt.

### 1. Lösungsansatz

Alle neuen Felder-Koordinaten berechnen und überprüfen, ob Koordinaten bereits bestehender Felder mit den neuen Koordinaten übereinstimmen.

### 2. Lösungsansatz

Die absolute Summe aller ∆direction der Indizes `i - 4` bis `i` darf nicht größer als 4 werden. `i` ist hierbei der Index des letzten Segments und es muss jeweils die Differenz zum vorherigen Segment bestimmt werden.

Beispielhafte Implementation in Java:
```java
private final List<Segment> segments = new ArrayList<>();

public List<Direction> getPossibleDirections(Direction current) {
    final Direction[] nextDirections = { current.rotate(-1), current, current.rotate(1) };
    final int segmentCount = segments.size();
    
    if (segmentCount >= 5) {
        int sum = 0;
        
        for (int i = segments.size() - 4; i < segments.size(); i++)
            sum += segments.get(i).direction().delta(segments.get(i - 1).direction());
    
        if (sum == -4)
            return Arrays.copyOfRange(nextDirections, 1, 3);
        else if (sum == 4)
            return Arrays.copyOfRange(nextDirections, 0, 2);
    }
    
    return nextDirections;
}
```

### Dein Betriebssystem?

Windows

**Comment by xeruf** [comment]
Danke für die detaillierte Info, da hast du echt den letzten kleinen edge case erwischt, ich hatte mir dazu nämlich auch schon Gedanken gemacht :sweat_smile:

**Comment by xeruf** [comment]
Meine Lösungsidee: Ein Segment darf niemals die entgegengesetzte Richtung des Segmentes drei Positionen vorher einnehmen. Ich denke das sollte das ganze elegant lösen.

**Comment by jgeramb** [comment]
Ja das sollte auch klappen, da bin ich gestern Nacht nicht drauf gekommen 😅

**Comment by jgeramb** [comment]
Dadurch wird allerdings eine U-förmige Map ebenfalls verhindert. Ich würde noch einen weiteren Check hinzufügen, ob dasselbe auch für `i - 1` und `i - 4` gilt. Dann würde ausschließlich der Kreis vermieden werden.

**Comment by jgeramb** [comment]
Ein Unit-Test für den Edge-Case wäre vermutlich auch angebracht ;)

**Comment by xeruf** [comment]
Thanks, wir besprechen das im PR :)
